// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKZDJzY8oOXk85uIUIBFYvMgZEW2yUtLY',
    appId: '1:489657803998:android:2826ac99b670ec26b70e4f',
    messagingSenderId: '489657803998',
    projectId: 'cash-coach',
    databaseURL: 'https://cash-coach-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cash-coach.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqWPDAcXsn6Rw-rH0EsFNyRnc6JDFTmWU',
    appId: '1:489657803998:ios:75f4c4a9d1e9ca39b70e4f',
    messagingSenderId: '489657803998',
    projectId: 'cash-coach',
    databaseURL: 'https://cash-coach-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cash-coach.appspot.com',
    androidClientId: '489657803998-q89m8dib5s5vj06jr45eckrlg4aoltuq.apps.googleusercontent.com',
    iosClientId: '489657803998-78f1f177c6kobrss3st969gk8bs8rcnj.apps.googleusercontent.com',
    iosBundleId: 'com.example.financeapp',
  );
}
